plugins {
    id 'java'
    id 'com.google.protobuf' version '0.9.6'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.apache.commons:commons-csv:1.10.0'
    implementation 'com.google.zxing:core:3.5.3'
    implementation 'com.google.zxing:javase:3.5.3'
    implementation 'com.fazecast:jSerialComm:2.10.4'

    // Protobuf runtime
    implementation 'com.google.protobuf:protobuf-java:4.34.1'

    // Testing
    testImplementation 'junit:junit:4.13.2'
}

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:4.34.1'
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}